/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dailycompetitiveprogramming;
    
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class LearnerFrame extends javax.swing.JFrame {
    String learnerName = "";
    /**
     * Creates new form LearnerFrame
     */
    public LearnerFrame() {
        initComponents();
    }
    public void setLeanerName(String learnerName){
        this.learnerName = learnerName;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        EnterMessage = new javax.swing.JLabel();
        EnterMessage1 = new javax.swing.JLabel();
        EnterMessage2 = new javax.swing.JLabel();
        EnterMessage3 = new javax.swing.JLabel();
        topicName = new javax.swing.JTextField();
        EnterTopic = new javax.swing.JButton();
        ViewTopic = new javax.swing.JButton();
        ViewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TopicArea = new javax.swing.JTextArea();
        mainMenu = new javax.swing.JButton();
        SolverMode = new javax.swing.JButton();
        mainMenu2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daily Competitive Programming - Learner Mode");
        setName("LearnerFrame"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(204, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Learner Mode - Learn with Me", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(102, 0, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter The Topic ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 204, 204))); // NOI18N

        EnterMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EnterMessage.setForeground(new java.awt.Color(255, 255, 255));
        EnterMessage.setText("Here, you can enter the new topic that you");

        EnterMessage1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EnterMessage1.setForeground(new java.awt.Color(255, 255, 255));
        EnterMessage1.setText("are learning everyday, every second. It");

        EnterMessage2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EnterMessage2.setForeground(new java.awt.Color(255, 255, 255));
        EnterMessage2.setText("will help you to keep track of your study");

        EnterMessage3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EnterMessage3.setForeground(new java.awt.Color(255, 255, 255));
        EnterMessage3.setText("also. Study now Learner!");

        topicName.setBackground(new java.awt.Color(255, 204, 255));
        topicName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        EnterTopic.setBackground(new java.awt.Color(204, 102, 255));
        EnterTopic.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EnterTopic.setForeground(new java.awt.Color(51, 0, 51));
        EnterTopic.setText("Enter New Topic");
        EnterTopic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EnterTopic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EnterTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterTopicActionPerformed(evt);
            }
        });

        ViewTopic.setBackground(new java.awt.Color(102, 102, 255));
        ViewTopic.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ViewTopic.setForeground(new java.awt.Color(51, 0, 51));
        ViewTopic.setText("View Learned Topics >>");
        ViewTopic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewTopic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTopicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(topicName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnterTopic, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnterMessage)
                            .addComponent(EnterMessage1)
                            .addComponent(EnterMessage2)
                            .addComponent(EnterMessage3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewTopic)
                .addGap(75, 75, 75))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EnterMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnterMessage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnterMessage2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnterMessage3)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterTopic, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(ViewTopic, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        ViewPanel.setBackground(new java.awt.Color(204, 255, 204));
        ViewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Learned Topics", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 0, 102))); // NOI18N
        ViewPanel.setForeground(new java.awt.Color(102, 0, 102));

        TopicArea.setEditable(false);
        TopicArea.setBackground(new java.awt.Color(255, 204, 204));
        TopicArea.setColumns(20);
        TopicArea.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TopicArea.setForeground(new java.awt.Color(51, 0, 51));
        TopicArea.setRows(5);
        jScrollPane1.setViewportView(TopicArea);

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        mainMenu.setBackground(new java.awt.Color(255, 153, 102));
        mainMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainMenu.setForeground(new java.awt.Color(102, 51, 0));
        mainMenu.setText("Main Menu");
        mainMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });

        SolverMode.setBackground(new java.awt.Color(255, 153, 102));
        SolverMode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SolverMode.setForeground(new java.awt.Color(102, 51, 0));
        SolverMode.setText("Solver Mode");
        SolverMode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SolverMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SolverMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolverModeActionPerformed(evt);
            }
        });

        mainMenu2.setBackground(new java.awt.Color(255, 153, 102));
        mainMenu2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainMenu2.setForeground(new java.awt.Color(102, 51, 0));
        mainMenu2.setText("Exit");
        mainMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SolverMode, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SolverMode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterTopicActionPerformed
        String topic = topicName.getText();
        Study programmingTopics = new Study(topic);
        programmingTopics.saveTopic();
        JOptionPane.showMessageDialog(this, "New Topic Added!");
        topicName.setText(null);
    }//GEN-LAST:event_EnterTopicActionPerformed

    private void ViewTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTopicActionPerformed
        Study programmingTopics = new Study("random");
        TopicArea.setText(programmingTopics.readTopic());
    }//GEN-LAST:event_ViewTopicActionPerformed

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        WelcomeFrame welcome = new WelcomeFrame();
        welcome.setVisible(true);
        dispose();
    }//GEN-LAST:event_mainMenuActionPerformed

    private void SolverModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolverModeActionPerformed
        SolverFrame solver = new SolverFrame();
        solver.setVisible(true);
        dispose();
    }//GEN-LAST:event_SolverModeActionPerformed

    private void mainMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenu2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mainMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnterMessage;
    private javax.swing.JLabel EnterMessage1;
    private javax.swing.JLabel EnterMessage2;
    private javax.swing.JLabel EnterMessage3;
    private javax.swing.JButton EnterTopic;
    private javax.swing.JButton SolverMode;
    private javax.swing.JTextArea TopicArea;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JButton ViewTopic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenu;
    private javax.swing.JButton mainMenu2;
    private javax.swing.JTextField topicName;
    // End of variables declaration//GEN-END:variables
}
