/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dailycompetitiveprogramming;

import java.lang.reflect.Array;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class OJModeFrame extends javax.swing.JFrame {

    /**
     * Creates new form OJModeFrame
     */
    public OJModeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OJPanel = new javax.swing.JPanel();
        Pending = new javax.swing.JPanel();
        GuideMessage = new javax.swing.JLabel();
        GuideMessage1 = new javax.swing.JLabel();
        GuideMessage2 = new javax.swing.JLabel();
        GuideMessage3 = new javax.swing.JLabel();
        GuideMessage4 = new javax.swing.JLabel();
        GuideMessage5 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        GuideMessage6 = new javax.swing.JLabel();
        GuideMessage7 = new javax.swing.JLabel();
        GuideMessage8 = new javax.swing.JLabel();
        GuideMessage9 = new javax.swing.JLabel();
        GuideMessage10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProblemListField = new javax.swing.JTextArea();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        addfield = new javax.swing.JTextField();
        GuideMessage11 = new javax.swing.JLabel();
        GuideMessage12 = new javax.swing.JLabel();
        contestpanel = new javax.swing.JPanel();
        GuideMessage13 = new javax.swing.JLabel();
        GuideMessage14 = new javax.swing.JLabel();
        GuideMessage15 = new javax.swing.JLabel();
        GuideMessage16 = new javax.swing.JLabel();
        GuideMessage17 = new javax.swing.JLabel();
        BotName = new javax.swing.JTextField();
        BotRatings = new javax.swing.JTextField();
        myRatings = new javax.swing.JTextField();
        compare = new javax.swing.JButton();
        GuideMessage18 = new javax.swing.JLabel();
        nameBots = new javax.swing.JTextField();
        ratingsee = new javax.swing.JButton();
        mainMenu = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daily Competitive Programming - OJ Dashboard");

        OJPanel.setBackground(new java.awt.Color(102, 153, 255));
        OJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Online Judge Tracking Dashboard", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        Pending.setBackground(new java.awt.Color(204, 204, 0));
        Pending.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pending Problems", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(102, 102, 0))); // NOI18N
        Pending.setForeground(new java.awt.Color(102, 102, 0));

        GuideMessage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage.setText("Here, you can insert the problems");

        GuideMessage1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage1.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage1.setText("you have to solve next. Problems");

        GuideMessage2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage2.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage2.setText("like wrong submission. So that you");

        GuideMessage3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage3.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage3.setText("don't forget to try the problem again.");

        GuideMessage4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage4.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage4.setText("Enter in this format(URI 1001). 1001");

        GuideMessage5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage5.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage5.setText("of uri is still not solved. List now!");

        view.setBackground(new java.awt.Color(255, 255, 204));
        view.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        view.setForeground(new java.awt.Color(51, 51, 0));
        view.setText("VIEW ");
        view.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        GuideMessage6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage6.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage6.setText("You can view the pending problem");

        GuideMessage7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage7.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage7.setText("list below. You can also cut the ");

        GuideMessage8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage8.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage8.setText("problem that is solved in the same");

        GuideMessage9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage9.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage9.setText("field. Simply add the ID or edit. Then ");

        GuideMessage10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage10.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage10.setText("Press Save. Save Now Coder!");

        ProblemListField.setBackground(new java.awt.Color(255, 255, 204));
        ProblemListField.setColumns(20);
        ProblemListField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ProblemListField.setForeground(new java.awt.Color(102, 102, 0));
        ProblemListField.setRows(5);
        jScrollPane1.setViewportView(ProblemListField);

        delete.setBackground(new java.awt.Color(255, 255, 204));
        delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(51, 51, 0));
        delete.setText("Delete");
        delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(255, 255, 204));
        add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 0));
        add.setText("ADD");
        add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        addfield.setBackground(new java.awt.Color(255, 255, 204));
        addfield.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addfield.setForeground(new java.awt.Color(102, 102, 0));

        GuideMessage11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage11.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage11.setText("View to delete a problem below first.");

        GuideMessage12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage12.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage12.setText("Otherwise list will be lost.");

        javax.swing.GroupLayout PendingLayout = new javax.swing.GroupLayout(Pending);
        Pending.setLayout(PendingLayout);
        PendingLayout.setHorizontalGroup(
            PendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PendingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GuideMessage)
                    .addComponent(GuideMessage1)
                    .addComponent(GuideMessage2)
                    .addComponent(GuideMessage3)
                    .addComponent(GuideMessage5)
                    .addComponent(GuideMessage4)
                    .addComponent(GuideMessage6)
                    .addComponent(GuideMessage7)
                    .addComponent(GuideMessage8)
                    .addComponent(GuideMessage10)
                    .addComponent(GuideMessage9, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PendingLayout.createSequentialGroup()
                        .addComponent(addfield, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GuideMessage11)
                    .addGroup(PendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PendingLayout.createSequentialGroup()
                            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GuideMessage12)))
        );
        PendingLayout.setVerticalGroup(
            PendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PendingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuideMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(addfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GuideMessage11)
                .addGap(5, 5, 5)
                .addComponent(GuideMessage12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        contestpanel.setBackground(new java.awt.Color(255, 51, 51));
        contestpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mini Contest with Bots", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        GuideMessage13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage13.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage13.setText("Here, there are some bots in this system.");

        GuideMessage14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage14.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage14.setText("These bots have some ratings based on ");

        GuideMessage15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage15.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage15.setText("Codeforces Contest. You can try to beat them.");

        GuideMessage16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage16.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage16.setText("Just Compare with them and keep beating. ");

        GuideMessage17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage17.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage17.setText("Don't Lose Hope Coder!");

        BotName.setEditable(false);

        BotRatings.setEditable(false);

        myRatings.setText("Just enter your ratings here. EX: 1040");

        compare.setBackground(new java.awt.Color(255, 153, 153));
        compare.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        compare.setForeground(new java.awt.Color(102, 0, 51));
        compare.setText("COMPARE");
        compare.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        compare.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        compare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareActionPerformed(evt);
            }
        });

        GuideMessage18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GuideMessage18.setForeground(new java.awt.Color(51, 51, 0));
        GuideMessage18.setText("write 1 for olives, 2 for star, 3 for rat");

        ratingsee.setBackground(new java.awt.Color(255, 153, 153));
        ratingsee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ratingsee.setForeground(new java.awt.Color(102, 0, 51));
        ratingsee.setText("See Rating");
        ratingsee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ratingsee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ratingsee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingseeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contestpanelLayout = new javax.swing.GroupLayout(contestpanel);
        contestpanel.setLayout(contestpanelLayout);
        contestpanelLayout.setHorizontalGroup(
            contestpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contestpanelLayout.createSequentialGroup()
                .addGroup(contestpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contestpanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(contestpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GuideMessage17)
                            .addComponent(GuideMessage15)
                            .addComponent(GuideMessage14)
                            .addComponent(GuideMessage13)
                            .addGroup(contestpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BotName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GuideMessage16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotRatings)
                                .addComponent(myRatings))
                            .addComponent(GuideMessage18)
                            .addGroup(contestpanelLayout.createSequentialGroup()
                                .addComponent(nameBots, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ratingsee, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contestpanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(compare, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        contestpanelLayout.setVerticalGroup(
            contestpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contestpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuideMessage13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GuideMessage14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GuideMessage15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GuideMessage16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GuideMessage17)
                .addGap(18, 18, 18)
                .addComponent(BotName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotRatings, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myRatings, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(compare, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuideMessage18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contestpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ratingsee, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(nameBots))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainMenu.setBackground(new java.awt.Color(255, 153, 102));
        mainMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainMenu.setForeground(new java.awt.Color(102, 51, 0));
        mainMenu.setText("Main Menu");
        mainMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(204, 204, 0));
        exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 102));
        exit.setText("Exit");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(204, 153, 0));
        back.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(102, 51, 0));
        back.setText("BACK");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OJPanelLayout = new javax.swing.GroupLayout(OJPanel);
        OJPanel.setLayout(OJPanelLayout);
        OJPanelLayout.setHorizontalGroup(
            OJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pending, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contestpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(OJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        OJPanelLayout.setVerticalGroup(
            OJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contestpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(OJPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        PendingProblem problemList = new PendingProblem("nothing");
        problemList.viewProblemList();
        ProblemListField.setText(problemList.viewProblemList());
    }//GEN-LAST:event_viewActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String problemField = ProblemListField.getText();
        PendingProblem problemList = new PendingProblem(problemField);
        problemList.editProblemList();
        JOptionPane.showMessageDialog(this, "Hurray!\nA Problem has been deleted!\nThat means you solved the problem\nKeep it up!");
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String problemField = addfield.getText();
        PendingProblem problemList = new PendingProblem(problemField);
        problemList.addProblemList();
        addfield.setText(null);
        JOptionPane.showMessageDialog(this, "Pending Problem Added");
    }//GEN-LAST:event_addActionPerformed

    private void compareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareActionPerformed
        String bots[] = {"Olive", "Star", "Rat"};
        int ratings[] = {600, 1200, 1800};
        int myRating = Integer.parseInt(myRatings.getText());
        BotName.setText(bots[0]+" "+bots[1]+" "+bots[2]);
        BotRatings.setText(Arrays.toString(ratings));
        for(int i=0;i<ratings.length;i++){
            
            if(myRating>ratings[i]) 
                JOptionPane.showMessageDialog(this, "You Just Beat " + bots[i]+"! Congratulations!");
        }
        JOptionPane.showMessageDialog(this, "Keep contesting! Soon you will beat my bots!");
    }//GEN-LAST:event_compareActionPerformed

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        WelcomeFrame welcome = new WelcomeFrame();
        welcome.setVisible(true);
        dispose();
    }//GEN-LAST:event_mainMenuActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       SolverFrame solver = new SolverFrame();
       solver.setVisible(true);
       dispose();
    }//GEN-LAST:event_backActionPerformed

    private void ratingseeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingseeActionPerformed
        int num = Integer.parseInt(nameBots.getText());
        int ratings[] = {600, 1200, 1800};
        try{
            JOptionPane.showMessageDialog(this, String.valueOf(ratings[num-1]));
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "You cannot take negative value");
        }
    }//GEN-LAST:event_ratingseeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OJModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OJModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OJModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OJModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OJModeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BotName;
    private javax.swing.JTextField BotRatings;
    private javax.swing.JLabel GuideMessage;
    private javax.swing.JLabel GuideMessage1;
    private javax.swing.JLabel GuideMessage10;
    private javax.swing.JLabel GuideMessage11;
    private javax.swing.JLabel GuideMessage12;
    private javax.swing.JLabel GuideMessage13;
    private javax.swing.JLabel GuideMessage14;
    private javax.swing.JLabel GuideMessage15;
    private javax.swing.JLabel GuideMessage16;
    private javax.swing.JLabel GuideMessage17;
    private javax.swing.JLabel GuideMessage18;
    private javax.swing.JLabel GuideMessage2;
    private javax.swing.JLabel GuideMessage3;
    private javax.swing.JLabel GuideMessage4;
    private javax.swing.JLabel GuideMessage5;
    private javax.swing.JLabel GuideMessage6;
    private javax.swing.JLabel GuideMessage7;
    private javax.swing.JLabel GuideMessage8;
    private javax.swing.JLabel GuideMessage9;
    private javax.swing.JPanel OJPanel;
    private javax.swing.JPanel Pending;
    private javax.swing.JTextArea ProblemListField;
    private javax.swing.JButton add;
    private javax.swing.JTextField addfield;
    private javax.swing.JButton back;
    private javax.swing.JButton compare;
    private javax.swing.JPanel contestpanel;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenu;
    private javax.swing.JTextField myRatings;
    private javax.swing.JTextField nameBots;
    private javax.swing.JButton ratingsee;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
