package dailycompetitiveprogramming;


import dailycompetitiveprogramming.WelcomeFrame;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class SolverFrame extends javax.swing.JFrame {
    String newSolverName = "";
    /**
     * Creates new form SolverFrame
     */
    public SolverFrame() {
        initComponents();
    }
    public void setSolverName(String newSolverName){
        this.newSolverName = newSolverName;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        SolverPanel1 = new javax.swing.JPanel();
        SolverPanel2 = new javax.swing.JPanel();
        SetTargetPanel = new javax.swing.JPanel();
        TargetMessage1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TargetMessage2 = new javax.swing.JLabel();
        TargetMessage3 = new javax.swing.JLabel();
        TargetMessage4 = new javax.swing.JLabel();
        targetfield = new javax.swing.JTextField();
        targetButton = new javax.swing.JButton();
        TargetMessage5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AddTotalMessage = new javax.swing.JLabel();
        AddTotalMessage1 = new javax.swing.JLabel();
        AddTotalMessage2 = new javax.swing.JLabel();
        AddTotalMessage3 = new javax.swing.JLabel();
        AddTotalMessage4 = new javax.swing.JLabel();
        SolvedateField = new javax.swing.JTextField();
        AddTotalSolveButton = new javax.swing.JButton();
        AddTotalSolveField = new javax.swing.JTextField();
        AddTotalMessage5 = new javax.swing.JLabel();
        AddTotalMessage6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultOfToday = new javax.swing.JTextArea();
        FeedbackGeneratorPanel = new javax.swing.JPanel();
        FeedbackMessage = new javax.swing.JLabel();
        FeedbackMessage1 = new javax.swing.JLabel();
        FeedbackMessage2 = new javax.swing.JLabel();
        FeedbackMessage3 = new javax.swing.JLabel();
        FeedbackMessage4 = new javax.swing.JLabel();
        FeedbackComboBox = new javax.swing.JComboBox<>();
        getfeedbutton = new javax.swing.JButton();
        Others = new javax.swing.JPanel();
        totalSolve = new javax.swing.JLabel();
        totalSolve1 = new javax.swing.JLabel();
        totalbutton = new javax.swing.JButton();
        TotalSolved = new javax.swing.JTextField();
        Progress = new javax.swing.JLabel();
        ProgressButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProgressArea = new javax.swing.JTextArea();
        MoreMenuPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        feed = new javax.swing.JTextArea();
        feedback = new javax.swing.JButton();
        Learner = new javax.swing.JButton();
        mainMenu = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        oJButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daily Competitive Programming - Dashboard");

        SolverPanel1.setBackground(new java.awt.Color(102, 102, 255));

        SolverPanel2.setBackground(new java.awt.Color(153, 102, 255));
        SolverPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Let's Start Programming Right Away!", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(204, 255, 255))); // NOI18N
        SolverPanel2.setForeground(new java.awt.Color(204, 255, 255));

        SetTargetPanel.setBackground(new java.awt.Color(0, 204, 0));
        SetTargetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Set Target", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 255, 255))); // NOI18N

        TargetMessage1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TargetMessage1.setForeground(new java.awt.Color(0, 102, 0));
        TargetMessage1.setText("Here, you can set a daily ");

        TargetMessage2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TargetMessage2.setForeground(new java.awt.Color(0, 102, 0));
        TargetMessage2.setText("target. This is the amount of");

        TargetMessage3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TargetMessage3.setForeground(new java.awt.Color(0, 102, 0));
        TargetMessage3.setText("total problems per day that you");

        TargetMessage4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TargetMessage4.setForeground(new java.awt.Color(0, 102, 0));
        TargetMessage4.setText("need to solve! If you haven't");

        targetfield.setBackground(new java.awt.Color(204, 255, 204));
        targetfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        targetfield.setForeground(new java.awt.Color(0, 102, 0));
        targetfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetfieldActionPerformed(evt);
            }
        });

        targetButton.setBackground(new java.awt.Color(102, 255, 102));
        targetButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        targetButton.setForeground(new java.awt.Color(0, 102, 0));
        targetButton.setText("SET NOW");
        targetButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        targetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        targetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetButtonActionPerformed(evt);
            }
        });

        TargetMessage5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TargetMessage5.setForeground(new java.awt.Color(0, 102, 0));
        TargetMessage5.setText("set yet, Set Now Coder!");

        javax.swing.GroupLayout SetTargetPanelLayout = new javax.swing.GroupLayout(SetTargetPanel);
        SetTargetPanel.setLayout(SetTargetPanelLayout);
        SetTargetPanelLayout.setHorizontalGroup(
            SetTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetTargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SetTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SetTargetPanelLayout.createSequentialGroup()
                        .addGroup(SetTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SetTargetPanelLayout.createSequentialGroup()
                                .addComponent(TargetMessage4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(SetTargetPanelLayout.createSequentialGroup()
                                .addComponent(targetfield, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(targetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(TargetMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TargetMessage3)
                    .addComponent(TargetMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TargetMessage5)))
        );
        SetTargetPanelLayout.setVerticalGroup(
            SetTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetTargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TargetMessage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TargetMessage2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TargetMessage3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TargetMessage4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TargetMessage5)
                .addGap(15, 15, 15)
                .addGroup(SetTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(targetfield, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(targetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Total Solve Daily", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 204, 204))); // NOI18N

        AddTotalMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddTotalMessage.setForeground(new java.awt.Color(102, 0, 0));
        AddTotalMessage.setText("Here, you have to insert the");

        AddTotalMessage1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddTotalMessage1.setForeground(new java.awt.Color(102, 0, 0));
        AddTotalMessage1.setText("amount of total problems");

        AddTotalMessage2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddTotalMessage2.setForeground(new java.awt.Color(102, 0, 0));
        AddTotalMessage2.setText("solved at the end of the day.");

        AddTotalMessage3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddTotalMessage3.setForeground(new java.awt.Color(102, 0, 0));
        AddTotalMessage3.setText("If you've solved enough");

        AddTotalMessage4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddTotalMessage4.setForeground(new java.awt.Color(102, 0, 0));
        AddTotalMessage4.setText("for today, add now Coder!");

        SolvedateField.setBackground(new java.awt.Color(255, 204, 204));
        SolvedateField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        AddTotalSolveButton.setBackground(new java.awt.Color(255, 153, 153));
        AddTotalSolveButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddTotalSolveButton.setForeground(new java.awt.Color(102, 0, 0));
        AddTotalSolveButton.setText("ADD NOW");
        AddTotalSolveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddTotalSolveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddTotalSolveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTotalSolveButtonActionPerformed(evt);
            }
        });

        AddTotalSolveField.setBackground(new java.awt.Color(255, 204, 204));
        AddTotalSolveField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        AddTotalMessage5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddTotalMessage5.setForeground(new java.awt.Color(102, 0, 0));
        AddTotalMessage5.setText("Enter Date:");

        AddTotalMessage6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddTotalMessage6.setForeground(new java.awt.Color(102, 0, 0));
        AddTotalMessage6.setText("Total Solve:");

        ResultOfToday.setEditable(false);
        ResultOfToday.setBackground(new java.awt.Color(255, 204, 204));
        ResultOfToday.setColumns(20);
        ResultOfToday.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ResultOfToday.setForeground(new java.awt.Color(102, 0, 0));
        ResultOfToday.setRows(5);
        jScrollPane1.setViewportView(ResultOfToday);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(AddTotalSolveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SolvedateField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddTotalMessage)
                            .addComponent(AddTotalMessage1)
                            .addComponent(AddTotalMessage2)
                            .addComponent(AddTotalMessage3)
                            .addComponent(AddTotalMessage4)
                            .addComponent(AddTotalMessage5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AddTotalMessage6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(AddTotalSolveField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddTotalMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddTotalMessage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddTotalMessage2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddTotalMessage3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddTotalMessage4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SolvedateField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTotalMessage5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddTotalSolveField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTotalMessage6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddTotalSolveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        FeedbackGeneratorPanel.setBackground(new java.awt.Color(51, 0, 255));
        FeedbackGeneratorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Feedback Generator", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 204, 255))); // NOI18N

        FeedbackMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        FeedbackMessage.setForeground(new java.awt.Color(0, 0, 102));
        FeedbackMessage.setText("Here, you can choose ");

        FeedbackMessage1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        FeedbackMessage1.setForeground(new java.awt.Color(0, 0, 102));
        FeedbackMessage1.setText("range of your percentage");

        FeedbackMessage2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        FeedbackMessage2.setForeground(new java.awt.Color(0, 0, 102));
        FeedbackMessage2.setText("to see feedbacks. It will");

        FeedbackMessage3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        FeedbackMessage3.setForeground(new java.awt.Color(0, 0, 102));
        FeedbackMessage3.setText("encourage you at the end");

        FeedbackMessage4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        FeedbackMessage4.setForeground(new java.awt.Color(0, 0, 102));
        FeedbackMessage4.setText("of the day. See now Coder!");

        FeedbackComboBox.setBackground(new java.awt.Color(204, 204, 255));
        FeedbackComboBox.setEditable(true);
        FeedbackComboBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        FeedbackComboBox.setForeground(new java.awt.Color(0, 51, 153));
        FeedbackComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "1-30%", "31-60%", "61-99%", "100%" }));
        FeedbackComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getfeedbutton.setBackground(new java.awt.Color(102, 102, 255));
        getfeedbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getfeedbutton.setForeground(new java.awt.Color(0, 0, 153));
        getfeedbutton.setText("See Now");
        getfeedbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getfeedbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getfeedbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getfeedbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FeedbackGeneratorPanelLayout = new javax.swing.GroupLayout(FeedbackGeneratorPanel);
        FeedbackGeneratorPanel.setLayout(FeedbackGeneratorPanelLayout);
        FeedbackGeneratorPanelLayout.setHorizontalGroup(
            FeedbackGeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackGeneratorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FeedbackGeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FeedbackMessage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FeedbackMessage4, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addGroup(FeedbackGeneratorPanelLayout.createSequentialGroup()
                        .addGroup(FeedbackGeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FeedbackMessage)
                            .addComponent(FeedbackMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(FeedbackGeneratorPanelLayout.createSequentialGroup()
                        .addComponent(FeedbackComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getfeedbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(FeedbackMessage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        FeedbackGeneratorPanelLayout.setVerticalGroup(
            FeedbackGeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackGeneratorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FeedbackMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FeedbackMessage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FeedbackMessage2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FeedbackMessage3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FeedbackMessage4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FeedbackGeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getfeedbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FeedbackComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        Others.setBackground(new java.awt.Color(153, 0, 153));
        Others.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Others", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 204, 255))); // NOI18N

        totalSolve.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalSolve.setForeground(new java.awt.Color(51, 0, 51));
        totalSolve.setText("Here you can view your total");

        totalSolve1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalSolve1.setForeground(new java.awt.Color(51, 0, 51));
        totalSolve1.setText("Solved this far and progress.");

        totalbutton.setBackground(new java.awt.Color(255, 153, 255));
        totalbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalbutton.setForeground(new java.awt.Color(153, 0, 153));
        totalbutton.setText("TOTAL");
        totalbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totalbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        totalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalbuttonActionPerformed(evt);
            }
        });

        TotalSolved.setEditable(false);
        TotalSolved.setBackground(new java.awt.Color(255, 204, 255));
        TotalSolved.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TotalSolved.setForeground(new java.awt.Color(153, 0, 153));

        Progress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Progress.setForeground(new java.awt.Color(51, 0, 51));
        Progress.setText("See Progress:");

        ProgressButton.setBackground(new java.awt.Color(255, 153, 255));
        ProgressButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProgressButton.setForeground(new java.awt.Color(153, 0, 153));
        ProgressButton.setText("Progress");
        ProgressButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProgressButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProgressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgressButtonActionPerformed(evt);
            }
        });

        ProgressArea.setEditable(false);
        ProgressArea.setBackground(new java.awt.Color(255, 204, 255));
        ProgressArea.setColumns(20);
        ProgressArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ProgressArea.setForeground(new java.awt.Color(153, 0, 153));
        ProgressArea.setRows(5);
        jScrollPane2.setViewportView(ProgressArea);

        javax.swing.GroupLayout OthersLayout = new javax.swing.GroupLayout(Others);
        Others.setLayout(OthersLayout);
        OthersLayout.setHorizontalGroup(
            OthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OthersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OthersLayout.createSequentialGroup()
                        .addComponent(totalSolve)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(OthersLayout.createSequentialGroup()
                        .addGroup(OthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalSolve1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(OthersLayout.createSequentialGroup()
                                .addGroup(OthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(totalbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Progress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(OthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalSolved)
                                    .addComponent(ProgressButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(77, 77, 77))))
        );
        OthersLayout.setVerticalGroup(
            OthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OthersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalSolve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalSolve1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalSolved, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProgressButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Progress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        MoreMenuPanel.setBackground(new java.awt.Color(255, 255, 51));
        MoreMenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "More Menu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 153, 102))); // NOI18N
        MoreMenuPanel.setForeground(new java.awt.Color(204, 204, 0));

        feed.setBackground(new java.awt.Color(255, 255, 204));
        feed.setColumns(20);
        feed.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        feed.setForeground(new java.awt.Color(153, 153, 0));
        feed.setRows(5);
        feed.setText("Give us some Feedback");
        jScrollPane4.setViewportView(feed);

        feedback.setBackground(new java.awt.Color(255, 255, 153));
        feedback.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        feedback.setForeground(new java.awt.Color(153, 153, 0));
        feedback.setText("Feedback");
        feedback.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        feedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackActionPerformed(evt);
            }
        });

        Learner.setBackground(new java.awt.Color(102, 255, 204));
        Learner.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Learner.setForeground(new java.awt.Color(0, 204, 153));
        Learner.setText("Learner Mode");
        Learner.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Learner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Learner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LearnerActionPerformed(evt);
            }
        });

        mainMenu.setBackground(new java.awt.Color(255, 153, 102));
        mainMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainMenu.setForeground(new java.awt.Color(102, 51, 0));
        mainMenu.setText("Main Menu");
        mainMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(204, 204, 0));
        exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 102));
        exit.setText("Exit");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        oJButton.setBackground(new java.awt.Color(153, 153, 255));
        oJButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        oJButton.setForeground(new java.awt.Color(0, 0, 204));
        oJButton.setText("OJ Mode");
        oJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        oJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MoreMenuPanelLayout = new javax.swing.GroupLayout(MoreMenuPanel);
        MoreMenuPanel.setLayout(MoreMenuPanelLayout);
        MoreMenuPanelLayout.setHorizontalGroup(
            MoreMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoreMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MoreMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MoreMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Learner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        MoreMenuPanelLayout.setVerticalGroup(
            MoreMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoreMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Learner, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(oJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SolverPanel2Layout = new javax.swing.GroupLayout(SolverPanel2);
        SolverPanel2.setLayout(SolverPanel2Layout);
        SolverPanel2Layout.setHorizontalGroup(
            SolverPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolverPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SolverPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SetTargetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Others, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SolverPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FeedbackGeneratorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MoreMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SolverPanel2Layout.setVerticalGroup(
            SolverPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolverPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SolverPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolverPanel2Layout.createSequentialGroup()
                        .addComponent(SetTargetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Others, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SolverPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(SolverPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(SolverPanel2Layout.createSequentialGroup()
                                .addComponent(FeedbackGeneratorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MoreMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout SolverPanel1Layout = new javax.swing.GroupLayout(SolverPanel1);
        SolverPanel1.setLayout(SolverPanel1Layout);
        SolverPanel1Layout.setHorizontalGroup(
            SolverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolverPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SolverPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SolverPanel1Layout.setVerticalGroup(
            SolverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolverPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SolverPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SolverPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SolverPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void targetfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetfieldActionPerformed

    private void ProgressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgressButtonActionPerformed
        SolvingProgress totalProgress = new SolvingProgress();
        ProgressArea.setText(String.valueOf(totalProgress.readAllProgressHistory()));
    }//GEN-LAST:event_ProgressButtonActionPerformed

    private void feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackActionPerformed
        String feedback;
        feedback = feed.getText();
        Feedback newFeed = new Feedback(feedback,newSolverName);
        newFeed.saveFeedbacks();
        feed.setText(null);
        JOptionPane.showMessageDialog(this, "Thank you for the feedback!");
    }//GEN-LAST:event_feedbackActionPerformed

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        WelcomeFrame welcome = new WelcomeFrame();
        welcome.setVisible(true);
        dispose();
    }//GEN-LAST:event_mainMenuActionPerformed

    private void targetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetButtonActionPerformed
        int target = 0;
        try{
            target = Integer.parseInt(targetfield.getText());
            Target newTarget = new Target(target);
            newTarget.saveTarget();
            targetfield.setText(null);
            JOptionPane.showMessageDialog(this, "Target has been saved");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid Input!");
        }
      
    }//GEN-LAST:event_targetButtonActionPerformed

    private void AddTotalSolveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTotalSolveButtonActionPerformed
        String dateOfSolving = SolvedateField.getText();
        String solvedProblems = AddTotalSolveField.getText();
        int totalProblems = 0;
        try{
            totalProblems = Integer.parseInt(solvedProblems);;
            TotalSolve solve = new TotalSolve(totalProblems);
            int target = solve.readTarget();
            try{
                System.out.println(totalProblems/target);
                solve.saveTotalSolveOverAll();
                Calculation progressOfTheDay = new Calculation(target,totalProblems,dateOfSolving);
                double percentage = progressOfTheDay.findAndSaveProgress();
                ResultOfToday.setText("Date: "+dateOfSolving+"\n"+"Total Solved: "+String.valueOf(totalProblems)+"\n"+"You have achieved "+String.valueOf(percentage)+"% of your goal!"+"\n");
                SolvedateField.setText(null);
                AddTotalSolveField.setText(null);
                JOptionPane.showMessageDialog(this, "Good Job Coder! See you tomorrow!");
            }
            catch(ArithmeticException e){
                JOptionPane.showMessageDialog(this, "Cannot take you further if you try to take a shortcut!\nYou cannot proceed with 0 target");
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid Input!");
        }
    }//GEN-LAST:event_AddTotalSolveButtonActionPerformed

    private void totalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalbuttonActionPerformed
        SolvingProgress totalSolved = new SolvingProgress();
        String amountOfProblemsSolved = String.valueOf(totalSolved.readTotalSolve());
        TotalSolved.setText(amountOfProblemsSolved+" Solved!");
    }//GEN-LAST:event_totalbuttonActionPerformed

    private void getfeedbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getfeedbuttonActionPerformed
        String rangePercentage = FeedbackComboBox.getItemAt(FeedbackComboBox.getSelectedIndex());
        if(rangePercentage.equals("0%")) JOptionPane.showMessageDialog(this, "You are not dedicated yet. CP world is a world of excitement.\nThere are coders like you rock everyday.\nPlease Start with me");
        else if(rangePercentage.equals("1-30%")) JOptionPane.showMessageDialog(this, "You are about to start competitive programming. Let's Go!");
        else if(rangePercentage.equals("31-60%")) JOptionPane.showMessageDialog(this, "You have to keep up with this streak.\nYou can do it!");
        else if(rangePercentage.equals("61-99%")) JOptionPane.showMessageDialog(this, "Just a little more hardwork will take\nyou to the world of competitive programming");
        else if(rangePercentage.equals("100%")) JOptionPane.showMessageDialog(this, "You just took off towards the competitive\nprogramming world. Good luck with your contest.\nSee you again tomorrow");
    }//GEN-LAST:event_getfeedbuttonActionPerformed

    private void LearnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LearnerActionPerformed
        LearnerLoginFrame learner = new LearnerLoginFrame();
        learner.setVisible(true);
        dispose();
    }//GEN-LAST:event_LearnerActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void oJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oJButtonActionPerformed
        OJModeFrame ojBoard = new OJModeFrame();
        ojBoard.setVisible(true);
        dispose();
    }//GEN-LAST:event_oJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolverFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddTotalMessage;
    private javax.swing.JLabel AddTotalMessage1;
    private javax.swing.JLabel AddTotalMessage2;
    private javax.swing.JLabel AddTotalMessage3;
    private javax.swing.JLabel AddTotalMessage4;
    private javax.swing.JLabel AddTotalMessage5;
    private javax.swing.JLabel AddTotalMessage6;
    private javax.swing.JButton AddTotalSolveButton;
    private javax.swing.JTextField AddTotalSolveField;
    private javax.swing.JComboBox<String> FeedbackComboBox;
    private javax.swing.JPanel FeedbackGeneratorPanel;
    private javax.swing.JLabel FeedbackMessage;
    private javax.swing.JLabel FeedbackMessage1;
    private javax.swing.JLabel FeedbackMessage2;
    private javax.swing.JLabel FeedbackMessage3;
    private javax.swing.JLabel FeedbackMessage4;
    private javax.swing.JButton Learner;
    private javax.swing.JPanel MoreMenuPanel;
    private javax.swing.JPanel Others;
    private javax.swing.JLabel Progress;
    private javax.swing.JTextArea ProgressArea;
    private javax.swing.JButton ProgressButton;
    private javax.swing.JTextArea ResultOfToday;
    private javax.swing.JPanel SetTargetPanel;
    private javax.swing.JTextField SolvedateField;
    private javax.swing.JPanel SolverPanel1;
    private javax.swing.JPanel SolverPanel2;
    private javax.swing.JLabel TargetMessage1;
    private javax.swing.JLabel TargetMessage2;
    private javax.swing.JLabel TargetMessage3;
    private javax.swing.JLabel TargetMessage4;
    private javax.swing.JLabel TargetMessage5;
    private javax.swing.JTextField TotalSolved;
    private javax.swing.JButton exit;
    private javax.swing.JTextArea feed;
    private javax.swing.JButton feedback;
    private javax.swing.JButton getfeedbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mainMenu;
    private javax.swing.JButton oJButton;
    private javax.swing.JButton targetButton;
    private javax.swing.JTextField targetfield;
    private javax.swing.JLabel totalSolve;
    private javax.swing.JLabel totalSolve1;
    private javax.swing.JButton totalbutton;
    // End of variables declaration//GEN-END:variables
}
