package dailycompetitiveprogramming;


import AdminResources.AdminFrame;
import dailycompetitiveprogramming.LoginFrame;
import dailycompetitiveprogramming.RegistrationFrame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class WelcomeFrame extends javax.swing.JFrame {
    //Global Variable Declaration Starts from here
    String newGuestName="";
    //Global Variable Declaration ends here
    
    /**
     * Creates new form WelcomeFrame
     */
    public WelcomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        WecomeMessage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Welcome1 = new javax.swing.JLabel();
        Welcome2 = new javax.swing.JLabel();
        Welcome3 = new javax.swing.JLabel();
        Mode = new javax.swing.JLabel();
        Guest = new javax.swing.JButton();
        register = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        jLabel1.setText("Enter As");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daily Competitive Programming - Home");
        setBackground(new java.awt.Color(102, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(153, 153, 255));
        setName("WecomeFrame"); // NOI18N

        WecomeMessage.setBackground(new java.awt.Color(102, 102, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 255), null, null));
        jPanel1.setAlignmentX(1.0F);

        Welcome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Welcome.setForeground(new java.awt.Color(0, 0, 153));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Welcome");

        Welcome1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Welcome1.setForeground(new java.awt.Color(0, 0, 153));
        Welcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome1.setText("To");

        Welcome2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Welcome2.setForeground(new java.awt.Color(0, 0, 153));
        Welcome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome2.setText("The World of");

        Welcome3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Welcome3.setForeground(new java.awt.Color(0, 0, 153));
        Welcome3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome3.setText("Competitive Programming");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(Welcome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(Welcome2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Welcome1)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Welcome3)
                        .addGap(79, 79, 79))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Welcome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Welcome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Welcome3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Mode.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Mode.setForeground(new java.awt.Color(255, 255, 255));
        Mode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mode.setText("Select Mode");
        Mode.setAlignmentX(0.5F);

        Guest.setBackground(new java.awt.Color(0, 204, 255));
        Guest.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Guest.setForeground(new java.awt.Color(0, 0, 102));
        Guest.setText("Enter as a Guest");
        Guest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Guest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(255, 51, 255));
        register.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        register.setForeground(new java.awt.Color(0, 0, 102));
        register.setText("Sign Up");
        register.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        LogIn.setBackground(new java.awt.Color(255, 0, 0));
        LogIn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LogIn.setForeground(new java.awt.Color(0, 0, 102));
        LogIn.setText("Sign In");
        LogIn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        Admin.setBackground(new java.awt.Color(0, 204, 0));
        Admin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Admin.setForeground(new java.awt.Color(0, 0, 102));
        Admin.setText("Admin");
        Admin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(204, 204, 0));
        exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 102));
        exit.setText("Exit");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WecomeMessageLayout = new javax.swing.GroupLayout(WecomeMessage);
        WecomeMessage.setLayout(WecomeMessageLayout);
        WecomeMessageLayout.setHorizontalGroup(
            WecomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WecomeMessageLayout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(WecomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WecomeMessageLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WecomeMessageLayout.createSequentialGroup()
                        .addComponent(Mode)
                        .addGap(340, 340, 340))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WecomeMessageLayout.createSequentialGroup()
                        .addGroup(WecomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Guest, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(325, 325, 325))))
        );
        WecomeMessageLayout.setVerticalGroup(
            WecomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WecomeMessageLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Mode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WecomeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WecomeMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestActionPerformed
        Guest newGuest = new Guest();//Generating Guest name
        newGuestName = newGuest.getGuestName();
        User newUser = new User(newGuestName, "123");
        newUser.saveUserName();
        GuestFrame Guest = new GuestFrame();
        Guest.setGuestName(newGuestName);
        Guest.setVisible(true);
        dispose();
    }//GEN-LAST:event_GuestActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        RegistrationFrame newSolver = new RegistrationFrame();
        newSolver.setVisible(true);
        dispose();
    }//GEN-LAST:event_registerActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        LoginFrame logInPage = new LoginFrame();
        logInPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogInActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        String AdminUserId = JOptionPane.showInputDialog("Enter Admin ID: ");
        if(AdminUserId.equals("alpha")){
            String AdminUserCode = JOptionPane.showInputDialog("Enter Your Code: ");
            if(AdminUserCode.equals("351866")){
                JOptionPane.showMessageDialog(this, "Access Granted!");
                AdminFrame admin = new AdminFrame();
                admin.setVisible(true);
                dispose();
            }
            else JOptionPane.showMessageDialog(this, "Access Denied!");
        }
        else JOptionPane.showMessageDialog(this, "Access Denied!");
    }//GEN-LAST:event_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton Guest;
    private javax.swing.JButton LogIn;
    private javax.swing.JLabel Mode;
    private javax.swing.JPanel WecomeMessage;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel Welcome1;
    private javax.swing.JLabel Welcome2;
    private javax.swing.JLabel Welcome3;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
